service: ipf-chatbots


provider:
  name: aws
  runtime: nodejs10.x
  region: ap-northeast-2
  profile: ipf
  apiName: ipf-chatbot-api
  memorySize: 256
  stage: dev

  tags:
    service: general
    environment: common
    owner: klee

  deploymentBucket:
    name: ipf-release-ci-seoul
    tags:
      service: general
      environment: common
      owner: klee

  role: arn:aws:iam::572836591883:role/ipf-chatbot

  environment:
    ENV: ${env:NODE_ENV, opt:alias}
    DYNAMODB_TABLE_NAME: ${env:DYNAMODB_TABLE_NAME}
    HEALTH_DATA_URL: ${env:HEALTH_DATA_URL}
    CASH_DISBURSEMENT_URL: ${env:CASH_DISBURSEMENT_URL}
    TZ: Asia/Seoul


package:
  individually: true
  exclude:
    - .nvmrc
    - .idea/**
    - README.md
    - health_methods.json
    - package*.json
    - auth.json
    - node_moduels/**
    - handler/**
    - business_logic/**
    - test/**
    - docs/**
    - src/**


plugins:
  - serverless-plugin-include-dependencies
  - serverless-offline
  - serverless-aws-alias
  - serverless-dotenv-plugin


functions:
  alarm-listen:
    handler: handler/alarm_bot.listenHandler
    events:
      - http:
          path: aws-alarm
          method: post

  alarm-event:
    handler: handler/alarm_bot.eventHandler
    events:
      - sns: ${env:SNS_ARN}
      - schedule: cron(0 1 ? * MON *)

  health-listen:
    handler: handler/health_bot.listenHandler
    events:
      - http:
          path: ipf-health
          method: post

  health-event:
    handler: handler/health_bot.eventHandler
    events:
      - schedule: cron(55 0-9 ? * MON-FRI *)

  youngmi-listen:
    handler: handler/youngmi_bot.listenHandler
    events:
      - http:
          path: ipf-youngmi
          method: post

  youngmi-event:
    handler: handler/youngmi_bot.eventHandler
    timeout: 30
    events:
      - schedule: cron(0 1 ? * MON-FRI *)

  docs-crawl:
    handler: handler/document_crawler.googleDocsCrawler
    timeout: 30
    events:
      - schedule: cron(0 0,5 ? * MON-FRI *)

  ipf-culture-docs:
    handler: handler/document_crawler.ipfCultureDocs
    events:
      - http:
          path: api/doc/{docId}
          method: get
          request:
            parameters:
              paths:
                docId: true
